[package]
name = "file-processor"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
xlib = { version = "0.1", path = "../../xlib" }

tokio = { version = "1", features = ["full"] }
tracing = "0.1"
anyhow = "1.0"
dotenv = "0.15.0"
serde_json = "1.0"
base64 = "0.22"
